## @file __metadata__.py
#  @brief: Set QApplication parameters
#
#  SPDX-FileCopyrightText: 2025 Christian Tosta
#  SPDX-License-Identifier: LGPL-3.0-only

# This file is automatically generated by CMake. Do not edit.

APPLICATION_ID = "com.ekaaty.shaman"
APPLICATION_NAME = "shaman"
APPLICATION_VERSION = "0.9.85"
ORGANIZATION_NAME = "Ekaaty"
ORGANIZATION_DOMAIN = "ekaaty.com"

# Vim modeline: :set ts=4:sw=4:sts=4:et
